### PR TITLE
id_number parameter added

### PR DESCRIPTION
**Pull request by ttozatto**
**Fixes issue:** #41 #21 
**Changes:**
I added the `id_number` parameter to the `CmcScraper` class. It overrides coin_code to avoid mistakes with repeated symbols.
`id_number` can be retrieved from [https://web-api.coinmarketcap.com/v1/cryptocurrency/map?symbol={SYMBOL}](https://web-api.coinmarketcap.com/v1/cryptocurrency/map?symbol=%7BSYMBOL%7D).
The URL above will give info about all tokens with the symbol provided.

### CODE REVIEW

**Comment by asdsadsaasd12312132** [comment]
How do I pass id_number? I tried CmcScraper("cosmos") but I got this error.

```
Error fetching coin id data for coin code {} cosmos
Error message: 'cosmos' coin code is unavailable on coinmarketcap.com
Error fetching price data for {} for interval '{}' and '{}' cosmos 28-4-2013 29-11-2022
Error message (download_data) : "slug" must only contain lowercase characters
Traceback (most recent call last):
  File "CoinMarketCap data downloader.py", line 14, in <module>
    headers, data = scraper.get_data()
  File "C:\Program Files\Python37\lib\site-packages\cryptocmd\core.py", line 126, in get_data
    self._download_data(**kwargs)
  File "C:\Program Files\Python37\lib\site-packages\cryptocmd\core.py", line 93, in _download_data
    for _row in coin_data["data"]["quotes"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by asdsadsaasd12312132** [comment]
Passing an id causes the first row/first trading date to be removed. I tested it with several coins (MATIC, 3890; ALGO, 4030; TWT, 5963). If the id is omitted, this doesn't happen.

**Comment by asdsadsaasd12312132** [comment]
The missing row seems to be due to an issue with the web-api. Using the slug instead of the coinid fixed this issue. I suggest changing coinid to slug.

https://web-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical?slug={}

**Comment by guptarohit** [comment]
Hi @ttozatto, thanks for the PR 💯 🔥 

Can we add `id_number` as and optional parameter not replacing `coin_code` to maintain the backward compatibility?

Also, it could be like: when `id_number` is passed we use it to fetch data instead the combination  of `coin_code` and `coin_name`.

Cheers!

**Comment by ttozatto** [comment]
Hi,

I can take a look at it this week, for sure.

Cheers! Have a great weekend!

Em sáb., 15 de jul. de 2023 13:13, Rohit Gupta ***@***.***>
escreveu:

**Comment by ttozatto** [comment]
Hi @guptarohit ,

I implemented what you suggested. If the user provides the optional parameter 'id_number', the code will ignore 'coin_code' and 'coin_name'. If 'coin_code' or 'coin_name' are different from the coin returned (from 'id_number') a warning will be displayed, so mistakes can be avoided. 

I made 'coin_code' optional, so a user can use 'id_number' alone.

Backward compatibility is maintained.

I also fixed in this PR two error messages.

**Pull request merged**
