### PR TITLE
allow to download price data in EUR and other fiat currencies

### PR DESCRIPTION
**Pull request by giocaizzi**
**Fixes issue:** 
Fixes issue of being able to download price data only in USD.

**Changes:**
* `cryptocmd.utils.download_coin_data` has new argument `fiat`, a string code to specify that price data is returned in the desired fiat currency eg. USD, EUR
* `cryptocmd.core.CmcScraper` has new attribute `fiat`. Default is `USD` but can now be changed during initialization.

### CODE REVIEW

**Comment by guptarohit** [comment]
Great changes @giocaizzi :+1: :cake:. Maybe it now would be great if we can include fiat in the default filename [core.py#L228](https://github.com/guptarohit/cryptoCMD/blob/master/cryptocmd/core.py#L228)

**Comment by giocaizzi** [comment]
good idea! 👍 i have added fiat in the default filename and modified the commented line just above it for clarity. [core.py#L191-L194](https://github.com/giocaizzi/cryptoCMD/blob/2c78f31b19b52ef8f9f4a693d3a662d175c64d92/cryptocmd/core.py#L191-L194)

**Comment by guptarohit** [comment]
@giocaizzi I guess we need to do similar changes on [core.py#L230-L231](https://github.com/giocaizzi/cryptoCMD/blob/2c78f31b19b52ef8f9f4a693d3a662d175c64d92/cryptocmd/core.py#L230-L231)

**Comment by giocaizzi** [comment]
oops, got confused between the two methods. added the same changes to `export`.

**Comment by guptarohit** [comment]
great changes @giocaizzi, thanks :smiley: :tada: :cake:

**Comment by giocaizzi** [comment]
@guptarohit when are you planning on releasing? I would really appreciate if this feature was available in the release on pypa 🚀

**Comment by guptarohit** [comment]
> @guptarohit when are you planning on releasing? I would really appreciate if this feature was available in the release on pypa 🚀

hey, I am planning to add GitHub actions for ci/cd to make releases with less friction, will do it very soon

**Comment by guptarohit** [comment]
hey @giocaizzi, FWIW these changes are now released on PyPI. :slightly_smiling_face: :v:

**Comment by giocaizzi** [comment]
@guptarohit great! Thanks 👍

**Pull request merged**
